name: Python app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        make dev_setup

    - name: Static analysis
      run: make static_analysis

    - name: Test
      run: make test
